#%RAML 1.0 DataType

type: object
properties:
  customerStateRequest:
    type: object
    properties:
      contactType:
        type: string
        required: true
        enum:
          - "mobile"
          - "email"
      countryCode:
        type: string
        required: true
        enum:
          - "+91"
          - "+1"
        example: "+91"
      mobile:
        type: string
        required: false
        example: "91111111254"
      email:
        type: string
        required: false
        example: "admin@admin.com"
      password:
        type: string
        required: true
        example: "hjfjjhvsadfv"
      status:
        type: boolean
        required: true
        example: true 